### ISSUE TITLE
Use of relations for image and sheet file names inside the spreadsheet files

### ISSUE THREAD

**Issue by sa3dany** [tanaikech/DocsServiceApp#3]
Hi @tanaikech, Thanks for making this library, it helped me at work deal with batch uploading product photos to an accounting system from Excel files.

While using the library, some `.xlsx` files had issues with the library due to the use of relationship files that map a specific drawing to filenames inside the Excel file. This also applies to linking sheet names to file names inside the Excel file. I've modified the library to work around this issue and get the file / image names from the relationship files.

I was wondering if you are using a build step for the code available here in the repo? If not I can open a pull request with my changes (which I am sure are not great since I made them in a hurry and I am not really familiar with the Excel file specifications and XML in general.)

**Comment by sa3dany** [comment]
I've emailed you two sample files.

Here's an example for the sheet file name stored in a relationship file:

## `xl/workbook.xml`
```XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  mc:Ignorable="x15 xr xr6 xr10 xr2"
  xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main"
  xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision"
  xmlns:xr6="http://schemas.microsoft.com/office/spreadsheetml/2016/revision6"
  xmlns:xr10="http://schemas.microsoft.com/office/spreadsheetml/2016/revision10"
  xmlns:xr2="http://schemas.microsoft.com/office/spreadsheetml/2015/revision2">
  <fileVersion appName="xl" lastEdited="7" lowestEdited="7" rupBuild="23801" />
  <workbookPr />
  ...
  <sheets>
    <sheet name="GLASSWARE" sheetId="3" r:id="rId1" />
  </sheets>
  ...
</workbook>
```

## `xl/_rels/workbook.xml.rels`
```XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml" />
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml" />
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml" />
  <Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/calcChain" Target="calcChain.xml" />
  <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml" />
</Relationships>
```

**Comment by sa3dany** [comment]
For my use case, I've already made changes to the library to support getting the drawing & sheet file names from these relations.

> For example, when you want to correspond each image file to your expected values, how about doing it after the image data was obtained from XLSX data? If this was not your expected direction, I apologize.

Right now without my modifications, the library will throw an error when using the `getImages()` method or the `getSheetByName()` depending on the usage of the `rels` file for image or sheet file names.

I can open a pull request so that you can review the modifications I've made.

**Comment by tanaikech** [comment]
Thank you for replying. About `Right now without my modifications, the library will throw an error when using the getImages() method or the getSheetByName() depending on the usage of the rels file for image or sheet file names.`, in this case, I would like to recommend to try to use the library after your XLSX was converted to Spreadsheet.

**Comment by sa3dany** [comment]
Thanks for the suggestion. You are right about converting to Google Spreadsheet before using the library, this seems to solve the issue with these relationships.  Feel free to close the issue.
